
services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379" # Открываем порт Redis для доступа извне
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Включаем сохранение данных на диск

volumes:
  redis_data:
    driver: local
